// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asset_manager.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Mb {
  public static partial class Bundle
  {
    static readonly string __ServiceName = "mb.Bundle";

    static readonly grpc::Marshaller<global::Mb.BundleRequest> __Marshaller_BundleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Mb.BundleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Mb.BundleResponse> __Marshaller_BundleResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Mb.BundleResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Mb.BundleRequest, global::Mb.BundleResponse> __Method_GetBundle = new grpc::Method<global::Mb.BundleRequest, global::Mb.BundleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetBundle",
        __Marshaller_BundleRequest,
        __Marshaller_BundleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Mb.AssetManagerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Bundle</summary>
    public abstract partial class BundleBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Mb.BundleResponse> GetBundle(global::Mb.BundleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Bundle</summary>
    public partial class BundleClient : grpc::ClientBase<BundleClient>
    {
      /// <summary>Creates a new client for Bundle</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BundleClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Bundle that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BundleClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BundleClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BundleClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Mb.BundleResponse GetBundle(global::Mb.BundleRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetBundle(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Mb.BundleResponse GetBundle(global::Mb.BundleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetBundle, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Mb.BundleResponse> GetBundleAsync(global::Mb.BundleRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetBundleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Mb.BundleResponse> GetBundleAsync(global::Mb.BundleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetBundle, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BundleClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BundleClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BundleBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetBundle, serviceImpl.GetBundle).Build();
    }

  }
  public static partial class Asset
  {
    static readonly string __ServiceName = "mb.Asset";

    static readonly grpc::Marshaller<global::Mb.AssetRequest> __Marshaller_AssetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Mb.AssetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Mb.AssetResponse> __Marshaller_AssetResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Mb.AssetResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Mb.AssetRequest, global::Mb.AssetResponse> __Method_GetAssets = new grpc::Method<global::Mb.AssetRequest, global::Mb.AssetResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "GetAssets",
        __Marshaller_AssetRequest,
        __Marshaller_AssetResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Mb.AssetManagerReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of Asset</summary>
    public abstract partial class AssetBase
    {
      public virtual global::System.Threading.Tasks.Task GetAssets(grpc::IAsyncStreamReader<global::Mb.AssetRequest> requestStream, grpc::IServerStreamWriter<global::Mb.AssetResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Asset</summary>
    public partial class AssetClient : grpc::ClientBase<AssetClient>
    {
      /// <summary>Creates a new client for Asset</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AssetClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Asset that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AssetClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AssetClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AssetClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Mb.AssetRequest, global::Mb.AssetResponse> GetAssets(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAssets(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Mb.AssetRequest, global::Mb.AssetResponse> GetAssets(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_GetAssets, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AssetClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AssetClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AssetBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAssets, serviceImpl.GetAssets).Build();
    }

  }
}
#endregion
